#!/bin/bash
##
# Create a new version tag at the current commit by incrementing the patch version of the most recent version tag.
##

# Set up the git credentials so we can push the tag back to GitHub
travis/git_credentials.bash

# Pick up the tags from the remote
git fetch --unshallow
git fetch --tags

echo "Branch: $(git branch -v | grep \*)"

# Get the last tag on this branch
LAST_TAG=$(git describe)
echo "INFO Last tag: $LAST_TAG"

# Build the new tag to push
NEW_TAG=$(LAST_TAG=${LAST_TAG} python travis/upversion.py)
echo "INFO Creating tag: $NEW_TAG"
git tag $NEW_TAG -a -m "Autogenerated version bump tag"

# Push the new tag
echo "INFO Pushing tag: $NEW_TAG"
git push origin $NEW_TAG
